baseURL: 'https://blog.szulinek.pl'
# languageCode: pl
title: IT Tech Anytime
theme: PaperMod


params:

    homeInfoParams:
        Title: Hello Stranger!
        Content: Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac tincidunt nulla. Praesent eleifend vel ligula vel convallis. Nulla ac mauris et risus molestie rhoncus sed eu arcu. Nam suscipit porta augue vel porttitor. Praesent varius quam ante, at auctor augue porttitor id. Nulla ut neque id justo posuere efficitur sed vel odio. Quisque a porttitor turpis. Ut gravida, arcu a ultrices pharetra, risus erat molestie sem, eget porttitor sapien nunc a neque..
    socialIcons:
      - name: facebook
        url: "https://facebook.com" 
      - name: github
        url: "https://github.com/hakue1990" 
      - name: youtube
        url: "https://youtube.com" 
      - name: url
        url: "https://szulinek.pl" 
      - name: linkedin
        url: "https://www.linkedin.com/in/adam-ha%C5%82da%C5%9B-49616a183/" 




### Add Image to a Hero Section

    profileMode:
        enabled: true
        title: "Web dev without a headache!" # optional default will be site title
        subtitle: "how about tech?"
        # imageUrl: "/img/monkey-dark.png" 
        
        buttons:
            - name: Archiwa
              url: "/archives/"
            - name: Kontakt
              url: "/contact/"



menu:
  main:


    - identifier: O mnie
      name: o mnie
      url: /about/
      weight: 10

    - identifier: usługi
      name: usługi
      url: /services/
      weight: 20

    # - identifier: kategorie
    #   name: kategorie
    #   url: /categories/
    #   weight: 50

    # - identifier: Tagi
    #   name: tags
    #   url: /tags/
    #   weight: 40

    - identifier: Posty
      name: posty
      url: /posts/
      layout: posts
      weight: 30

    - identifier: Kontakt
      name: kontakt
      url: /contact/
      weight: 40

    - identifier: szulinek.pl
      name: portfolio
      url: https://szulinek.pl
      weight: 80
    - identifier: Portfolio
  
minify:
  disableXML: true
  minifyOutput: true











## Szukanie ##

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary