baseURL: ''
languageCode: en-us
title: My kitchen Blog :)
theme: PaperMod


params:

    homeInfoParams:
        Title: Siema, witaj na moim blogu!
        Content: Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac tincidunt nulla. Praesent eleifend vel ligula vel convallis. Nulla ac mauris et risus molestie rhoncus sed eu arcu. Nam suscipit porta augue vel porttitor. Praesent varius quam ante, at auctor augue porttitor id. Nulla ut neque id justo posuere efficitur sed vel odio. Quisque a porttitor turpis. Ut gravida, arcu a ultrices pharetra, risus erat molestie sem, eget porttitor sapien nunc a neque..

menu:
  main:
    - identifier: kategorie
      name: kategorie
      url: /kategorie/
      weight: 10
    - identifier: Tagi
      name: tags
      url: /tags/
      weight: 20
      
    # - identifier: example
    #   name: szulinek.pl
    #   url: https://szulinek.pl
    #   weight: 40
    # - identifier: Archiwa
    #   name: archiwa
    #   url: /archiwa/
    #   weight: 30
  
minify:
  disableXML: true
  minifyOutput: true





  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"





## Szukanie ##

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary