baseURL: "https://szulinek.pl"
#languageCode: ["pl", "en"]
title: IT Tech Anytime
theme: PaperMod




enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

## Poniższy parametr jest kluczowy jeśli chodzi wielojęzyczność
defaultContentLanguage: pl
defaultContentLanguageInSubdir: true
languages:
  pl:
    languageName: ":pl:"
    languageAltTitle: Polski
    weight: 2
    title: IT Tech Anytime
    # taxonomies:
    #   category: FRcategories
    #   tag: FRtags
    #   series: FRseries
    profileMode:
      enabled: true
      title: IT bez bólu głowy!
      subtitle: "☄️ Szybko | ☁️ Płynnie | 🌙 Zwinnie | 📱 Responsywnie"
      imageUrl: "/img/dark.png" # optional
      imageTitle: "szulinek the fox" # optional
      imageWidth: 370 # custom size
      imageHeight: 300 # custom size
      buttons:
        - name: Blog
          url: posts
        - name: Kontakt
          url: /pl/contact/
    menu:
      main:
        - name: Whoami
          url: about
          weight: 5
        - name: Usługi
          url: services/
          weight: 10
        - name: Blog
          url: posts/
          weight: 15
        - name: Strony www
          url: /pl/www/
          weight: 16
        - name: Kontakt
          url: contact/
          weight: 20
        - name: Archiwa
          url: /pl/archives/
          weight: 20


########### END POLISH ##########
########### ENGLISH ##########

  en:
    languageName: ":en:"
    languageAltTitle: English
    weight: 2
    title: IT Tech Anytime
    
    # taxonomies:
    #   category: FRcategories
    #   tag: FRtags
    #   series: FRseries
    profileMode:
      enabled: true
      title: IT without a headache!
      subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"

      imageUrl: "/img/dark.png" # optional
      imageTitle: "szulinek the fox" # optional

      imageWidth: 370 # custom size
      imageHeight: 300 # custom size
      buttons:
        - name: Blog
          url: /en/posts
        - name: Contact
          url: /en/contact
    menu:
      main:
        - name: Whoami
          url: /en/about
          weight: 5
        - name: Services
          url: /en/services/
          weight: 10
        - name: Blog
          url: /en/posts/
          weight: 15
        - name: Contact
          url: /en/contact/
          weight: 20
        - name: Archives
          url: /en/archives/
          weight: 20
        # - name: Search
        #   url: search
        #   weight: 25

  ########### END ENGLISH ##########
params:
  ShowCodeCopyButtons: true
  defaultTheme: dark
  homeInfoParams:
  socialIcons:
    - name: github
      url: "https://github.com/hakue1990"
    - name: url
      url: "https://szulinek.pl"
    - name: linkedin
      url: "https://www.linkedin.com/in/adam-ha%C5%82da%C5%9B-49616a183/"
## add Logo to Navbar
  label:
        text: "Szulinek IT"
        icon: "/img/coding.png"
        iconHeight: 40


