baseURL: "https://szulinek.pl"
languageCode: ["pl", "en"]
title: IT Tech Anytime
theme: PaperMod




enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true




minify:
  disableXML: true
  minifyOutput: true


## Poniższy parametr jest kluczowy jeśli chodzi wielojęzyczność
defaultContentLanguage: pl
defaultContentLanguageInSubdir: true
languages:
  pl:
    languageName: ":pl:"
    languageAltTitle: Polski
    weight: 2
    title: IT Tech Anytime
    # taxonomies:
    #   category: FRcategories
    #   tag: FRtags
    #   series: FRseries
    profileMode:
      enabled: true
      title: IT bez bólu głowy!
      subtitle: "☄️ Szybko | ☁️ Płynnie | 🌙 Zwinnie | 📱 Responsywnie"
      buttons:
        - name: Blog
          url: posts
        - name: Kontakt
          url: /contact/
    menu:
      main:
        - name: O mnie
          url: about
          weight: 5
        - name: Usługi
          url: services/
          weight: 10
        - name: Blog
          url: posts/
          weight: 15
        - name: Kontakt
          url: contact/
          weight: 20
        - name: Portfolio
          url: https://portfolio.szulinek.pl#projects
          weight: 25
  en:
    languageName: ":en:"
    languageAltTitle: English
    weight: 2
    title: IT Tech Anytime
    # taxonomies:
    #   category: FRcategories
    #   tag: FRtags
    #   series: FRseries
    profileMode:
      enabled: true
      title: IT without a headache!
      subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
      buttons:
        - name: Blog
          url: /en/posts
        - name: Contact
          url: /en//contact
    menu:
      main:
        - name: About
          url: /en/about
          weight: 5
        - name: Services
          url: /en/services/
          weight: 10
        - name: Blog
          url: /en/posts/
          weight: 15
        - name: Contact
          url: /en/contact/
          weight: 20
        - name: Portfolio
          url: https://portfolio.szulinek.pl#projects
          weight: 25
  
params:
  defaultTheme: dark
  homeInfoParams:
    Title: Hello Stranger!
    Content: Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ac tincidunt nulla. Praesent eleifend vel ligula vel convallis. Nulla ac mauris et risus molestie rhoncus sed eu arcu. Nam suscipit porta augue vel porttitor. Praesent varius quam ante, at auctor augue porttitor id. Nulla ut neque id justo posuere efficitur sed vel odio. Quisque a porttitor turpis. Ut gravida, arcu a ultrices pharetra, risus erat molestie sem, eget porttitor sapien nunc a neque..
  socialIcons:
    - name: github
      url: "https://github.com/hakue1990"
    - name: url
      url: "https://szulinek.pl"
    - name: linkedin
      url: "https://www.linkedin.com/in/adam-ha%C5%82da%C5%9B-49616a183/"

## add Logo
  label:
        text: "Szulinek.pl"
        icon: "/img/coding.png"
        iconHeight: 35

### Add Image to a Hero Section

  profileMode:
    enabled: true
    title: "Tech without a headache!" # optional default will be site title
    subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"

    buttons:
      - name: Archives
        url: "/en/archives/"
      - name: Contact
        url: "/en/contact/"
